# Generated by Django 4.2 on 2023-04-13 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="compagny",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["category"],},
        ),
        migrations.CreateModel(
            name="CompagnyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "compagnycategory",
                "verbose_name_plural": "compagnycategories",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="compagnycategory",
            index=models.Index(fields=["name"], name="companies_c_name_70530c_idx"),
        ),
        migrations.AddField(
            model_name="compagny",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="companies.compagnycategory",
            ),
        ),
        migrations.AddIndex(
            model_name="compagny",
            index=models.Index(fields=["id", "slug"], name="companies_c_id_fd5b5a_idx"),
        ),
        migrations.AddIndex(
            model_name="compagny",
            index=models.Index(
                fields=["category"], name="companies_c_categor_c1f0b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="compagny",
            index=models.Index(
                fields=["-created"], name="companies_c_created_d77f33_idx"
            ),
        ),
    ]
