# Generated by Django 4.2 on 2023-04-11 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="addresses",),
        migrations.RemoveField(model_name="user", name="zip_code",),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="addresses.address",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="country",
                to="addresses.country",
            ),
        ),
    ]
