# Generated by Django 4.2 on 2023-04-09 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="K_bis",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="addresses",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compagnycategory",
                to="companies.compagnycategory",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="civility",
            field=models.CharField(
                choices=[("Masculin", "Masculin"), ("Féminin", "Féminin")],
                default="",
                max_length=8,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compagny",
                to="companies.compagny",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="phone_mobile",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="zip_code",
            field=models.CharField(default="", max_length=5),
            preserve_default=False,
        ),
    ]
