# Generated by Django 4.2 on 2023-04-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_addresses_remove_user_zip_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="email", field=models.CharField(max_length=100),
        ),
    ]
