# Generated by Django 4.2 on 2023-04-10 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("users", "0002_user_k_bis_user_addresses_user_category_user_city_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="user", options={"ordering": ["category"]},),
        migrations.RemoveField(model_name="user", name="company",),
        migrations.AddField(
            model_name="user",
            name="compagny",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compagny",
                to="companies.compagnycategory",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["id", "slug"], name="users_user_id_2ac0eb_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["category"], name="users_user_categor_5081c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["-created"], name="users_user_created_513ca1_idx"
            ),
        ),
    ]
