# Generated by Django 4.2 on 2023-04-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="username",),
    ]
