# Generated by Django 4.2 on 2023-04-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_username"),
    ]

    operations = [
        migrations.RenameField(model_name="user", old_name="K_bis", new_name="k_bis",),
    ]
