# Generated by Django 4.2 on 2023-04-27 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("users", "0008_alter_user_civility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="compagny",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compagny",
                to="companies.compagnycategory",
            ),
        ),
    ]
